#!/usr/bin/env bash
# dev.sh — bootstrap dependencies and start all local development services
#
# Usage:  ./dev.sh
#
# What it does:
#   1. Creates / updates the root .venv and installs Python deps
#   2. Installs Playwright's Chromium browser for board capture
#   3. Installs Node.js deps for apps/web
#   4. Derives apps/web/.env.local from the root .env
#   5. Starts uvicorn (API :8000) and Next.js (Web :3000) side-by-side

set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
VENV="$ROOT/.venv"
WEB_DIR="$ROOT/apps/web"
API_REQ="$ROOT/apps/api/requirements.txt"

# ── Terminal colours ──────────────────────────────────────────────────────────
if [[ -t 1 ]]; then
  BOLD=$'\033[1m'; RESET=$'\033[0m'
  RED=$'\033[0;31m'; GREEN=$'\033[0;32m'
  YELLOW=$'\033[1;33m'; CYAN=$'\033[0;36m'; MAGENTA=$'\033[0;35m'
else
  BOLD=''; RESET=''; RED=''; GREEN=''; YELLOW=''; CYAN=''; MAGENTA=''
fi

step()    { printf '  %s▸%s  %s\n' "$CYAN"    "$RESET" "$*"; }
ok()      { printf '  %s✓%s  %s\n' "$GREEN"   "$RESET" "$*"; }
warn()    { printf '  %s⚠%s  %s\n' "$YELLOW"  "$RESET" "$*"; }
die()     { printf '  %s✗%s  %s\n' "$RED"     "$RESET" "$*" >&2; exit 1; }
section() { printf '\n%s%s%s\n' "$BOLD" "$*" "$RESET"; }

# ── 1. Prerequisites ──────────────────────────────────────────────────────────
section "Prerequisites"

command -v python3 &>/dev/null || die "python3 not found — install Python 3.11+."
command -v node    &>/dev/null || die "node not found — install Node.js 20+."
command -v npm     &>/dev/null || die "npm not found."

ok "python3 $(python3 --version 2>&1 | awk '{print $2}') · node $(node --version) · npm $(npm --version)"

# ── 2. Root .env ──────────────────────────────────────────────────────────────
section "Environment"

if [[ ! -f "$ROOT/.env" ]]; then
  step "No root .env found — creating from templates..."
  {
    cat "$ROOT/apps/api/.env.example"
    echo ""
    cat "$ROOT/apps/web/.env.example"
  } > "$ROOT/.env"
  warn "Created .env — fill in DATABASE_URL, GEMINI_API_KEY, and CRON_SECRET before running the API."
fi

# Load root .env so all child processes inherit the variables
set -a
# shellcheck source=/dev/null
source "$ROOT/.env"
set +a
ok "Loaded .env"

# Warn about unfilled placeholder values
for var in DATABASE_URL GEMINI_API_KEY CRON_SECRET; do
  val="${!var:-}"
  if [[ -z "$val" || "$val" == *"replace"* || "$val" == *"your-"* || "$val" == *"password"* ]]; then
    warn "\$${var} looks unset or is still a placeholder"
  fi
done

# Write Next.js env file — Next.js only reads .env.local from its own directory
{
  printf '# Auto-generated by dev.sh — edit the root .env instead\n'
  printf 'API_BASE_URL=%s\n' "${API_BASE_URL:-http://127.0.0.1:8000}"
  printf 'CRON_SECRET=%s\n'  "${CRON_SECRET:-}"
} > "$WEB_DIR/.env.local"
ok "Wrote apps/web/.env.local"

# ── 3. Python environment ─────────────────────────────────────────────────────
section "Python"

if [[ ! -f "$VENV/bin/python" ]]; then
  step "Creating virtual environment..."
  python3 -m venv "$VENV"
  ok "Created .venv"
fi

step "Installing Python dependencies..."
"$VENV/bin/pip" install --quiet --upgrade pip
"$VENV/bin/pip" install --quiet -r "$API_REQ"
ok "Python dependencies up to date"

# Playwright — install Chromium if the browser binary is missing
step "Checking Playwright browsers..."
if ! "$VENV/bin/python" -c "
from playwright.sync_api import sync_playwright
with sync_playwright() as p:
    p.chromium.launch().close()
" &>/dev/null 2>&1; then
  step "Installing Chromium for Playwright..."
  "$VENV/bin/playwright" install chromium
fi
ok "Playwright Chromium ready"

# ── 4. Node.js dependencies ───────────────────────────────────────────────────
section "Node.js"

step "Installing npm packages..."
npm install --prefix "$WEB_DIR" --silent
ok "Node.js dependencies up to date"

# ── 5. Start services ─────────────────────────────────────────────────────────
section "Starting services"

API_PID=""
WEB_PID=""

cleanup() {
  printf '\n  %s▸%s  Shutting down...\n' "$YELLOW" "$RESET"
  [[ -n "$API_PID" ]] && kill "$API_PID" 2>/dev/null || true
  [[ -n "$WEB_PID" ]] && kill "$WEB_PID" 2>/dev/null || true
  wait 2>/dev/null || true
}
trap cleanup INT TERM

printf '\n  %sAPI%s  →  http://127.0.0.1:8000\n' "$MAGENTA" "$RESET"
printf   '  %sWeb%s  →  http://localhost:3000\n'  "$CYAN"    "$RESET"
printf   '\n  Press %sCtrl-C%s to stop.\n\n' "$BOLD" "$RESET"

# uvicorn must run from root so that `apps.api.*` and `solver.*` imports resolve
"$VENV/bin/uvicorn" apps.api.main:app \
  --reload \
  --host 127.0.0.1 \
  --port 8000 \
  2>&1 | awk -v p="  ${MAGENTA}[api]${RESET}  " '{print p $0; fflush()}' &
API_PID=$!

(cd "$WEB_DIR" && npm run dev) \
  2>&1 | awk -v p="  ${CYAN}[web]${RESET}  " '{print p $0; fflush()}' &
WEB_PID=$!

wait
