import gymnasium as gym
import pygame
import numpy as np
import importlib.util
from pathlib import Path
from typing import Optional

class TicTacWorldEnv(gym.Env):
    metadata = {"render_modes": ["human", "rgb_array"], "render_fps": 4}
    training_board_counts = {1: 15, 2: 30, 3: 50, 4: 75, 5: 75, 6: 75, 7: 75, 8: 75, 9: 50}
    training_boards_file = Path(__file__).resolve().parents[2] / "generated_training_boards.py"
    training_boards = None

    @classmethod
    def get_training_boards(cls):
        if cls.training_boards is not None:
            return cls.training_boards

        if cls.training_boards_file.exists():
            spec = importlib.util.spec_from_file_location("generated_training_boards", cls.training_boards_file)
            generated_boards = importlib.util.module_from_spec(spec)
            spec.loader.exec_module(generated_boards)
            cls.training_boards = generated_boards.TRAINING_BOARDS
            return cls.training_boards

        generator_path = Path(__file__).resolve().parents[2] / "board_generator.py"
        spec = importlib.util.spec_from_file_location("board_generator", generator_path)
        board_generator = importlib.util.module_from_spec(spec)
        spec.loader.exec_module(board_generator)

        generator = board_generator.BoardGenerator()
        cls.training_boards = {}
        for grad_num in cls.training_board_counts:
            count = cls.training_board_counts[grad_num]
            fixed_os = ((1, 1), (2, 1)) if grad_num == 1 else None
            cls.training_boards[grad_num] = generator.generate(
                grad=grad_num,
                count=count,
                fixed_os=fixed_os,
                seed=grad_num,
                verbose=False,
            )

        cls.save_training_boards()
        return cls.training_boards

    @classmethod
    def save_training_boards(cls):
        lines = [
            "# Auto-generated by TicTacWorldEnv. Delete this file to regenerate boards.\n",
            "TRAINING_BOARDS = {\n",
        ]
        for grad_num in sorted(cls.training_boards):
            lines.append(f"    {grad_num}: [\n")
            for board in cls.training_boards[grad_num]:
                lines.append("        (\n")
                for row in board:
                    lines.append(f"            {row!r},\n")
                lines.append("        ),\n")
            lines.append("    ],\n")
        lines.append("}\n")
        cls.training_boards_file.write_text("".join(lines))

    def __init__(self, length=8, width=8, board = tuple(tuple()), render_mode=None, reset_option=8):
        self.length = length
        self.width = width
        self.board = board
        self.base_board = tuple(tuple(row) for row in board)
        self.initial_board = tuple(tuple(row) for row in board)
        self.render_mode = render_mode
        self.window_size = 512
        self.window = None
        self.clock = None
        self.reset_option = reset_option

        assert self.render_mode is None or self.render_mode in self.metadata["render_modes"]

        self.agentX = -1
        self.agentY = -1
        self.oOneX = -1
        self.oOneY = -1
        self.oTwoX = -1
        self.oTwoY = -1
        self.initialAgentX = -1
        self.initialAgentY = -1
        self.initialOOneX = -1
        self.initialOOneY = -1
        self.initialOTwoX = -1
        self.initialOTwoY = -1

        try:
            for i in range(0, len(board)):
                for j in range(0, len(board[i])):
                    if board[i][j] == "U":
                        self.agentX = i
                        self.agentY = j
                        self.initialAgentX = i
                        self.initialAgentY = j
                        raise StopIteration
        except StopIteration:
            pass
        
        try:
            for i in range(0, len(board)):
                for j in range(0, len(board[i])):
                    if board[i][j] == "O" and self.oTwoX == -1:
                        self.oOneX = i
                        self.oOneY = j
                        self.initialOOneX = i
                        self.initialOOneY = j
                    if board[i][j] == "O" and self.oTwoX != -1:
                        self.oTwoX = i
                        self.oTwoY = j
                        self.initialOTwoX = i
                        self.initialOTwoY = j
                        raise StopIteration
        except StopIteration:
            pass


        self.agent_location = np.array([self.agentX, self.agentY], dtype=np.int32)
        self.o_one_location = np.array([self.oOneX, self.oOneY], dtype=np.int32)
        self.o_two_location = np.array([self.oTwoX, self.oTwoY], dtype=np.int32)
        
        self.observation_space = gym.spaces.Box(low = 0, 
                                                high = 1,
                                                shape=(5, 8, 8), 
                                                dtype=np.int32)

        self.action_space = gym.spaces.Discrete(4)
    
    def moveUp(self, board=None):
        if board is None:
            board = self.board
        userPos = self.agent_location.copy()
        
        if userPos[0]-1 >= 0 :
            if board[userPos[0]-1][userPos[1]] == "B" :
                return board, self.agent_location, self.o_one_location, self.o_two_location
            elif((board[userPos[0]-1][userPos[1]] == "X" or 
                board[userPos[0]-1][userPos[1]] == "O")
                and (
                    userPos[0]-2 < 0 or board[userPos[0]-2][userPos[1]] != "")):
                return board, self.agent_location, self.o_one_location, self.o_two_location
            else:

                newBoard = [list(row) for row in board]
                if(userPos[0]-2 >= 0 and board[userPos[0]-1][userPos[1]] == "X"):
                    newBoard[userPos[0]-2][userPos[1]] = newBoard[userPos[0]-1][userPos[1]]

                elif(userPos[0]-2 >= 0 and board[userPos[0]-1][userPos[1]] == "O"):
                    if(userPos[0]-1 == self.o_one_location[0] and userPos[1] == self.o_one_location[1]):
                        self.o_one_location[0] = self.o_one_location[0] - 1
                    elif(userPos[0]-1 == self.o_two_location[0] and userPos[1] == self.o_two_location[1]):
                        self.o_two_location[0] = self.o_two_location[0] - 1

                    newBoard[userPos[0]-2][userPos[1]] = newBoard[userPos[0]-1][userPos[1]]

                newBoard[userPos[0]-1][userPos[1]] = "U"
                self.agent_location[0] = self.agent_location[0] - 1
                newBoard[userPos[0]][userPos[1]] = ""
                self.board = newBoard

                return tuple(tuple(row) for row in newBoard), self.agent_location, self.o_one_location, self.o_two_location
        return board, self.agent_location, self.o_one_location, self.o_two_location

    def moveRight(self, board=None):
        if board is None:
            board = self.board
        userPos = self.agent_location.copy()
        
        if userPos[1]+1 < len(board[0]):
            if board[userPos[0]][userPos[1]+1] == "B":
                return board, self.agent_location, self.o_one_location, self.o_two_location
            elif ((board[userPos[0]][userPos[1]+1] == "X" or 
                board[userPos[0]][userPos[1]+1] == "O")
                and (userPos[1]+2 >= len(board[0]) or board[userPos[0]][userPos[1]+2] != "")):
                return board, self.agent_location, self.o_one_location, self.o_two_location
            else:
                newBoard = [list(row) for row in board]
                
                if (userPos[1]+2 < len(board[0]) and board[userPos[0]][userPos[1]+1] == "X"):
                    newBoard[userPos[0]][userPos[1]+2] = newBoard[userPos[0]][userPos[1]+1]

                elif (userPos[1]+2 < len(board[0]) and board[userPos[0]][userPos[1]+1] == "O"):
                    if (userPos[0] == self.o_one_location[0] and userPos[1]+1 == self.o_one_location[1]):
                        self.o_one_location[1] = self.o_one_location[1] + 1
                    elif (userPos[0] == self.o_two_location[0] and userPos[1]+1 == self.o_two_location[1]):
                        self.o_two_location[1] = self.o_two_location[1] + 1

                    newBoard[userPos[0]][userPos[1]+2] = newBoard[userPos[0]][userPos[1]+1]

                newBoard[userPos[0]][userPos[1]+1] = "U"
                self.agent_location[1] = self.agent_location[1] + 1
                newBoard[userPos[0]][userPos[1]] = ""
                self.board = newBoard

                return tuple(tuple(row) for row in newBoard), self.agent_location, self.o_one_location, self.o_two_location
                
        return board, self.agent_location, self.o_one_location, self.o_two_location

    def moveLeft(self, board=None):
        if board is None:
            board = self.board
        userPos = self.agent_location.copy()
        
        if userPos[1]-1 >= 0:
            if board[userPos[0]][userPos[1]-1] == "B":
                return board, self.agent_location, self.o_one_location, self.o_two_location
            elif ((board[userPos[0]][userPos[1]-1] == "X" or 
                board[userPos[0]][userPos[1]-1] == "O")
                and (userPos[1]-2 < 0 or board[userPos[0]][userPos[1]-2] != "")):
                return board, self.agent_location, self.o_one_location, self.o_two_location
            else:
                newBoard = [list(row) for row in board]
                
                if (userPos[1]-2 >= 0 and board[userPos[0]][userPos[1]-1] == "X"):
                    newBoard[userPos[0]][userPos[1]-2] = newBoard[userPos[0]][userPos[1]-1]

                elif (userPos[1]-2 >= 0 and board[userPos[0]][userPos[1]-1] == "O"):
                    if (userPos[0] == self.o_one_location[0] and userPos[1]-1 == self.o_one_location[1]):
                        self.o_one_location[1] = self.o_one_location[1] - 1
                    elif (userPos[0] == self.o_two_location[0] and userPos[1]-1 == self.o_two_location[1]):
                        self.o_two_location[1] = self.o_two_location[1] - 1

                    newBoard[userPos[0]][userPos[1]-2] = newBoard[userPos[0]][userPos[1]-1]

                newBoard[userPos[0]][userPos[1]-1] = "U"
                self.agent_location[1] = self.agent_location[1] - 1
                newBoard[userPos[0]][userPos[1]] = ""
                self.board = newBoard

                return tuple(tuple(row) for row in newBoard), self.agent_location, self.o_one_location, self.o_two_location
                
        return board, self.agent_location, self.o_one_location, self.o_two_location

    def moveDown(self, board=None):
        if board is None:
            board = self.board
        userPos = self.agent_location.copy()
        
        if userPos[0]+1 < len(board):
            if board[userPos[0]+1][userPos[1]] == "B":
                return board, self.agent_location, self.o_one_location, self.o_two_location
            elif ((board[userPos[0]+1][userPos[1]] == "X" or 
                board[userPos[0]+1][userPos[1]] == "O")
                and (userPos[0]+2 >= len(board) or board[userPos[0]+2][userPos[1]] != "")):
                return board, self.agent_location, self.o_one_location, self.o_two_location
            else:
                newBoard = [list(row) for row in board]
                
                if (userPos[0]+2 < len(board) and board[userPos[0]+1][userPos[1]] == "X"):
                    newBoard[userPos[0]+2][userPos[1]] = newBoard[userPos[0]+1][userPos[1]]

                elif (userPos[0]+2 < len(board) and board[userPos[0]+1][userPos[1]] == "O"):
                    if (userPos[0]+1 == self.o_one_location[0] and userPos[1] == self.o_one_location[1]):
                        self.o_one_location[0] = self.o_one_location[0] + 1
                    elif (userPos[0]+1 == self.o_two_location[0] and userPos[1] == self.o_two_location[1]):
                        self.o_two_location[0] = self.o_two_location[0] + 1

                    newBoard[userPos[0]+2][userPos[1]] = newBoard[userPos[0]+1][userPos[1]]

                newBoard[userPos[0]+1][userPos[1]] = "U"
                self.agent_location[0] = self.agent_location[0] + 1
                newBoard[userPos[0]][userPos[1]] = ""
                self.board = newBoard

                return tuple(tuple(row) for row in newBoard), self.agent_location, self.o_one_location, self.o_two_location
                
        return board, self.agent_location, self.o_one_location, self.o_two_location

    def lostCheck(self, board=None):
        if board is None:
            board = self.board
        for i in range(0, len(board)):
            for j in range(0, len(board[i]) - 2):
                if board[i][j] == "X" and board[i][j + 1] == "X" and board[i][j + 2] == "X":
                    return True

        for i in range(0, len(board) - 2):
            for j in range(0, len(board[i])):
                if board[i][j] == "X" and board[i + 1][j] == "X" and board[i + 2][j] == "X":
                    return True

        return False

    def solved(self, board=None):
        if board is None:
            board = self.board
        for i in range(0, len(board)):
            for j in range(0, len(board[i]) - 2):
                if board[i][j] in ("O", "U") and board[i][j + 1] in ("O", "U") and board[i][j + 2] in ("O", "U"):
                    return True

        for i in range(0, len(board) - 2):
            for j in range(0, len(board[i])):
                if board[i][j] in ("O", "U") and board[i + 1][j] in ("O", "U") and board[i + 2][j] in ("O", "U"):
                    return True

        return False

    def softLocked(self, board=None):
        if board is None:
            board = self.board

        def in_bounds(row, col):
            return 0 <= row < len(board) and 0 <= col < len(board[row])

        def x_is_movable(row, col):
            directions = [(-1, 0), (1, 0), (0, -1), (0, 1)]

            for row_change, col_change in directions:
                push_from_row = row - row_change
                push_from_col = col - col_change
                push_to_row = row + row_change
                push_to_col = col + col_change

                if not in_bounds(push_from_row, push_from_col):
                    continue
                if not in_bounds(push_to_row, push_to_col):
                    continue
                if board[push_from_row][push_from_col] not in ("", "U"):
                    continue
                if board[push_to_row][push_to_col] == "":
                    return True

            return False

        def spot_can_become_user(row, col):
            if board[row][col] in ("", "U"):
                return True
            if board[row][col] == "X":
                return x_is_movable(row, col)
            return False

        def spot_can_become_empty(row, col):
            if board[row][col] == "":
                return True
            if board[row][col] == "X":
                return x_is_movable(row, col)
            return False

        def o_is_movable(row, col):
            directions = [(-1, 0), (1, 0), (0, -1), (0, 1)]

            for row_change, col_change in directions:
                push_from_row = row - row_change
                push_from_col = col - col_change
                push_to_row = row + row_change
                push_to_col = col + col_change

                if not in_bounds(push_from_row, push_from_col):
                    continue
                if not in_bounds(push_to_row, push_to_col):
                    continue
                if not spot_can_become_user(push_from_row, push_from_col):
                    continue
                if spot_can_become_empty(push_to_row, push_to_col):
                    return True

            return False

        def o_can_move_direction(row, col, row_change, col_change):
            push_from_row = row - row_change
            push_from_col = col - col_change
            push_to_row = row + row_change
            push_to_col = col + col_change

            if not in_bounds(push_from_row, push_from_col):
                return False
            if not in_bounds(push_to_row, push_to_col):
                return False
            if not spot_can_become_user(push_from_row, push_from_col):
                return False
            return spot_can_become_empty(push_to_row, push_to_col)

        o_locations = []
        for i in range(0, len(board)):
            for j in range(0, len(board[i])):
                if board[i][j] == "O":
                    o_locations.append((i, j))

        if len(o_locations) == 2:
            first_o, second_o = o_locations
            os_are_aligned = first_o[0] == second_o[0] or first_o[1] == second_o[1]
            if not os_are_aligned:
                first_o_movable = o_is_movable(first_o[0], first_o[1])
                second_o_movable = o_is_movable(second_o[0], second_o[1])
                if not first_o_movable and not second_o_movable:
                    return True

                left_o, right_o = sorted(o_locations, key=lambda location: location[1])
                if right_o[1] - left_o[1] > 2:
                    left_can_move_right = o_can_move_direction(left_o[0], left_o[1], 0, 1)
                    right_can_move_left = o_can_move_direction(right_o[0], right_o[1], 0, -1)
                    if not left_can_move_right and not right_can_move_left:
                        return True

                top_o, bottom_o = sorted(o_locations, key=lambda location: location[0])
                if bottom_o[0] - top_o[0] > 2:
                    top_can_move_down = o_can_move_direction(top_o[0], top_o[1], 1, 0)
                    bottom_can_move_up = o_can_move_direction(bottom_o[0], bottom_o[1], -1, 0)
                    if not top_can_move_down and not bottom_can_move_up:
                        return True

        found_two_os_in_line = False

        for i in range(0, len(board)):
            for j in range(0, len(board[i]) - 2):
                line = [board[i][j], board[i][j + 1], board[i][j + 2]]
                if line.count("O") == 2:
                    found_two_os_in_line = True
                    for col in range(j, j + 3):
                        if board[i][col] != "O" and spot_can_become_user(i, col):
                            return False

        for i in range(0, len(board) - 2):
            for j in range(0, len(board[i])):
                line = [board[i][j], board[i + 1][j], board[i + 2][j]]
                if line.count("O") == 2:
                    found_two_os_in_line = True
                    for row in range(i, i + 3):
                        if board[row][j] != "O" and spot_can_become_user(row, j):
                            return False

        return found_two_os_in_line


    def _get_obs(self):

        mapping = {"":0, "X":1, "O":2, "U":3, "B":4}
        arr = [[mapping[cell] for cell in row] for row in self.board]

        compatibleBoard = np.array(arr, dtype=np.int32)

        threeDArr = np.zeros((5, 8, 8), dtype=np.int32)

        for i in range(0, len(compatibleBoard)):
                for j in range(0, len(compatibleBoard[i])):
                    if compatibleBoard[i][j] == 0:
                        threeDArr[0][i][j] = 1
                    elif compatibleBoard[i][j] == 1:
                        threeDArr[1][i][j] = 1
                    elif compatibleBoard[i][j] == 2:
                        threeDArr[2][i][j] = 1
                    elif compatibleBoard[i][j] == 3:
                        threeDArr[3][i][j] = 1
                    elif compatibleBoard[i][j] == 4:
                        threeDArr[4][i][j] = 1

        return threeDArr
    
    def _get_info(self):
        boardString = ""
        for row in self.board:
            boardString += " ".join([cell if cell != "" else "." for cell in row])
        return dict(board=boardString)
    
    def reset(self, seed: Optional[int] = None, options= None):
        super().reset(seed = seed)

        if(options is None):
            options = self.reset_option

        grad = options if options in self.training_board_counts else 9
        boards = self.get_training_boards()[grad]

        for _ in range(len(boards)):
            selected_board = boards[np.random.randint(len(boards))]
            self.board = [list(row) for row in selected_board]
            if not self.softLocked(self.board):
                break
        else:
            selected_board = boards[np.random.randint(len(boards))]
            self.board = [list(row) for row in selected_board]

        length = 0
        width = 0
        for i in range(len(self.board)):
            for j in range(len(self.board[i])):
                if(self.board[i][j] != "B"):
                    if(i>length-1):
                        length = i+1
                    if(j>width-1):
                        width = j+1
        
        if(length == 0):
            length = len(self.board)
        if(width == 0):
            width = len(self.board[0])

        self.length = length
        self.width = width
        self.initial_board = tuple(tuple(row) for row in self.board)

        self.agentX = -1
        self.agentY = -1
        self.oOneX = -1
        self.oOneY = -1
        self.oTwoX = -1
        self.oTwoY = -1
        self.initialAgentX = -1
        self.initialAgentY = -1
        self.initialOOneX = -1
        self.initialOOneY = -1
        self.initialOTwoX = -1
        self.initialOTwoY = -1

        try:
            for i in range(0, len(self.board)):
                for j in range(0, len(self.board[i])):
                    if self.board[i][j] == "U":
                        self.agentX = i
                        self.agentY = j
                        self.initialAgentX = i
                        self.initialAgentY = j
                        raise StopIteration
        except StopIteration:
            pass
        
        try:
            for i in range(0, len(self.board)):
                for j in range(0, len(self.board[i])):
                    if self.board[i][j] == "O" and self.oTwoX == -1:
                        self.oOneX = i
                        self.oOneY = j
                        self.initialOOneX = i
                        self.initialOOneY = j
                    if self.board[i][j] == "O" and self.oTwoX != -1:
                        self.oTwoX = i
                        self.oTwoY = j
                        self.initialOTwoX = i
                        self.initialOTwoY = j
                        raise StopIteration
        except StopIteration:
            pass

        self.agent_location = np.array([self.agentX, self.agentY], dtype=np.int32)
        self.o_one_location = np.array([self.oOneX, self.oOneY], dtype=np.int32)
        self.o_two_location = np.array([self.oTwoX, self.oTwoY], dtype=np.int32)
        self.board = tuple(tuple(row) for row in self.initial_board)

        observation = self._get_obs()
        info = self._get_info()

        if self.render_mode == "human":
            self._render_frame()

        return observation, info
    
    def step(self, action):

        currentPos = self.agent_location.copy()

        if action == 0:
            self.moveUp()
        elif action == 1:
            self.moveDown()
        elif action == 2:
            self.moveLeft()
        elif action == 3:
            self.moveRight()

        same = False
        if currentPos[0] == self.agent_location[0] and currentPos[1] == self.agent_location[1]:
            same = True

        won = self.solved()
        lost = self.lostCheck()
        softLocked = self.softLocked()

        terminated = won or lost
        truncated = False

        #Negative per step scales with size
        reward = -0.5 * (16 / (self.length * self.width))

        if softLocked:
            terminated = True
            reward += -10

        if same:
            reward += -1

        if lost:
            reward += -10
        elif won:
            reward += 40
        
        observation = self._get_obs()
        info = self._get_info()

        if self.render_mode == "human":
            self._render_frame()

        return observation, reward, terminated, truncated, info

    def render(self):
        if self.render_mode == "rgb_array":
            return self._render_frame()

    def _render_frame(self):
        if self.window is None and self.render_mode == "human":
            pygame.init()
            pygame.display.init()
            self.window = pygame.display.set_mode((self.window_size, self.window_size))
            pygame.display.set_caption("Tic Tac Go")

        if self.clock is None and self.render_mode == "human":
            self.clock = pygame.time.Clock()

        canvas = pygame.Surface((self.window_size, self.window_size))
        canvas.fill((245, 245, 245))

        rows = len(self.board)
        cols = len(self.board[0]) if rows > 0 else 0
        if rows == 0 or cols == 0:
            if self.render_mode == "human":
                self.window.blit(canvas, canvas.get_rect())
                pygame.event.pump()
                pygame.display.update()
                self.clock.tick(self.metadata["render_fps"])
                return None

            return np.transpose(
                np.array(pygame.surfarray.pixels3d(canvas)), axes=(1, 0, 2)
            )

        cell_size = self.window_size / max(rows, cols)
        board_width = cols * cell_size
        board_height = rows * cell_size
        x_offset = (self.window_size - board_width) / 2
        y_offset = (self.window_size - board_height) / 2

        colors = {
            "": (255, 255, 255),
            "B": (45, 45, 45),
            "X": (52, 116, 235),
            "O": (235, 88, 52),
            "U": (61, 168, 86),
        }

        for row_index, row in enumerate(self.board):
            for col_index, cell in enumerate(row):
                rect = pygame.Rect(
                    x_offset + col_index * cell_size,
                    y_offset + row_index * cell_size,
                    cell_size,
                    cell_size,
                )
                pygame.draw.rect(canvas, colors.get(cell, (230, 230, 230)), rect)
                pygame.draw.rect(canvas, (30, 30, 30), rect, width=2)

                center = rect.center
                radius = max(4, int(cell_size * 0.28))
                if cell == "X":
                    padding = cell_size * 0.25
                    pygame.draw.line(
                        canvas,
                        (255, 255, 255),
                        (rect.left + padding, rect.top + padding),
                        (rect.right - padding, rect.bottom - padding),
                        width=max(2, int(cell_size * 0.08)),
                    )
                    pygame.draw.line(
                        canvas,
                        (255, 255, 255),
                        (rect.right - padding, rect.top + padding),
                        (rect.left + padding, rect.bottom - padding),
                        width=max(2, int(cell_size * 0.08)),
                    )
                elif cell == "O":
                    pygame.draw.circle(
                        canvas,
                        (255, 255, 255),
                        center,
                        radius,
                        width=max(2, int(cell_size * 0.08)),
                    )
                elif cell == "U":
                    pygame.draw.circle(canvas, (255, 255, 255), center, radius)

        if self.render_mode == "human":
            self.window.blit(canvas, canvas.get_rect())
            pygame.event.pump()
            pygame.display.update()
            self.clock.tick(self.metadata["render_fps"])
            return None

        return np.transpose(
            np.array(pygame.surfarray.pixels3d(canvas)), axes=(1, 0, 2)
        )

    def close(self):
        if self.window is not None:
            pygame.display.quit()
            pygame.quit()
            self.window = None
            self.clock = None
        
        

        
