import multiprocessing as mp
from pathlib import Path

from board_generator import BoardGenerator


OUTPUT_PATH = Path(__file__).resolve().parent / "generated_boards_4_to_8.py"
TIMEOUT_SECONDS = 25
BOARD_COUNTS = {
    4: 50,
    5: 50,
    6: 50,
    7: 50,
    8: 50,
}


def generate_one(args):
    grad_num, seed = args
    generator = BoardGenerator()
    return generator.generate(
        grad=grad_num,
        count=1,
        seed=seed,
        verbose=False,
    )[0]


def write_boards(training_boards):
    lines = [
        "# Generated by generate_boards_4_to_8.py.\n",
        "# This file is separate from generated_training_boards.py.\n",
        "TRAINING_BOARDS_4_TO_8 = {\n",
    ]
    for grad_num in sorted(training_boards):
        lines.append(f"    {grad_num}: [\n")
        for board in training_boards[grad_num]:
            lines.append("        (\n")
            for row in board:
                lines.append(f"            {row!r},\n")
            lines.append("        ),\n")
        lines.append("    ],\n")
    lines.append("}\n")
    OUTPUT_PATH.write_text("".join(lines))


def main():
    training_boards = {}

    for grad_num, count in BOARD_COUNTS.items():
        print(f"Generating grad {grad_num}: {count} boards", flush=True)
        boards = []
        seen = set()
        seed = grad_num
        timed_out = 0

        with mp.Pool(processes=1) as pool:
            while len(boards) < count:
                result = pool.apply_async(generate_one, ((grad_num, seed),))
                try:
                    board = result.get(timeout=TIMEOUT_SECONDS)
                except mp.TimeoutError:
                    pool.terminate()
                    pool.join()
                    timed_out += 1
                    print(f"  seed={seed} timed out; accepted={len(boards)}", flush=True)
                    pool = mp.Pool(processes=1)
                else:
                    if board not in seen:
                        seen.add(board)
                        boards.append(board)
                        print(f"  accepted {len(boards)}/{count} seed={seed}", flush=True)
                        training_boards[grad_num] = boards
                        write_boards(training_boards)
                seed += 1

        training_boards[grad_num] = boards
        write_boards(training_boards)
        print(f"Finished grad {grad_num}; skipped {timed_out} timed-out seeds", flush=True)

    print(f"Saved boards to {OUTPUT_PATH}", flush=True)


if __name__ == "__main__":
    main()
