"""Generate BFS-solved injection boards for DQN grads 11-15.

This script writes generated boards and solution strings into injection_boards.py
inside the auto-generated block. Existing hand-written injections are preserved.
"""

from __future__ import annotations

import contextlib
import io
import pprint
import random
import signal
from collections import defaultdict
from concurrent.futures import ProcessPoolExecutor, as_completed
from pathlib import Path

from BFStoTrainer import BFStoTrainer
from board_generator import BoardGenerator


GRADS = (11, 12, 13, 14, 15)
BOARDS_PER_GRAD = 100
GENERATED_CANDIDATES_PER_GRAD = 2000
BFS_TIMEOUT_SECONDS = 30
WORKERS = 6
MAX_CANDIDATE_LAYOUT_ATTEMPTS = 50
INJECTION_PATH = Path(__file__).resolve().parent / "injection_boards.py"
ALL_SOLVED_OUTPUT_PATH = (
    Path(__file__).resolve().parent / "generated_solved_injections_11_to_15.py"
)

START_MARKER = "# AUTO-GENERATED GRAD 11-15 INJECTIONS START"
END_MARKER = "# AUTO-GENERATED GRAD 11-15 INJECTIONS END"

ACTION_NAMES = "UDLR"


class BfsTimeout(Exception):
    pass


def _timeout_handler(_signum, _frame):
    raise BfsTimeout


def _solve_with_timeout(board, grad):
    solver = BFStoTrainer()
    signal.signal(signal.SIGALRM, _timeout_handler)
    signal.alarm(BFS_TIMEOUT_SECONDS)
    try:
        with contextlib.redirect_stdout(io.StringIO()):
            dataset = solver.solve(
                board,
                current_grad=grad,
                terminate_on_repeated_states=False,
                penalize_repeated_states=False,
            )
    finally:
        signal.alarm(0)

    if not dataset:
        return None
    return "".join(ACTION_NAMES[step["action"]] for step in dataset)


def _candidate_board(generator, grad):
    candidate = generator._generate_candidate(grad)
    if candidate is None:
        return None

    board_2d = candidate["board"]
    if not generator._os_can_align(board_2d):
        return None

    return generator._to_key(board_2d)


def generate_one(task):
    grad, candidate_number, seed = task
    random.seed(seed)
    generator = BoardGenerator()

    for _ in range(MAX_CANDIDATE_LAYOUT_ATTEMPTS):
        board = _candidate_board(generator, grad)
        if board is None:
            continue

        try:
            solution = _solve_with_timeout(board, grad)
        except BfsTimeout:
            continue

        if solution:
            return grad, candidate_number, board, solution

    return grad, candidate_number, None, None


def build_generated_block(generated_by_grad):
    lines = [
        START_MARKER,
        "# Generated by solver/gymnasium_register/generate_injections_11_to_15.py",
        "GENERATED_INJECTION_BY_GRAD = ",
        pprint.pformat(generated_by_grad, width=100, sort_dicts=True),
        END_MARKER,
    ]
    return "\n".join(lines)


def update_injection_file(generated_by_grad):
    text = INJECTION_PATH.read_text(encoding="utf-8")
    start = text.index(START_MARKER)
    end = text.index(END_MARKER, start) + len(END_MARKER)
    new_text = (
        text[:start]
        + build_generated_block(generated_by_grad)
        + text[end:]
    )
    INJECTION_PATH.write_text(new_text, encoding="utf-8")


def write_all_solved_candidates(solved_candidates):
    all_solved_by_grad = {}
    for grad in GRADS:
        sorted_candidates = sorted(
            solved_candidates[grad],
            key=lambda item: (item[0], -item[1]),
            reverse=True,
        )
        all_solved_by_grad[grad] = [
            {
                "solution_length": solution_length,
                "candidate_number": candidate_number,
                "board": board,
                "solution": solution,
            }
            for solution_length, candidate_number, board, solution
            in sorted_candidates
        ]

    lines = [
        "# All BFS-solved injection candidates generated by",
        "# solver/gymnasium_register/generate_injections_11_to_15.py",
        "# Sorted hardest-first within each grad.",
        "ALL_SOLVED_INJECTION_CANDIDATES = ",
        pprint.pformat(all_solved_by_grad, width=100, sort_dicts=True),
        "",
    ]
    ALL_SOLVED_OUTPUT_PATH.write_text("\n".join(lines), encoding="utf-8")


def main():
    solved_candidates = defaultdict(list)
    seen_boards = {grad: set() for grad in GRADS}
    seed_rng = random.Random()

    tasks = [
        (grad, candidate_number, seed_rng.randrange(2**32))
        for grad in GRADS
        for candidate_number in range(1, GENERATED_CANDIDATES_PER_GRAD + 1)
    ]
    completed_by_grad = {grad: 0 for grad in GRADS}

    with ProcessPoolExecutor(max_workers=WORKERS) as executor:
        futures = [executor.submit(generate_one, task) for task in tasks]

        for future in as_completed(futures):
            grad, candidate_number, board, solution = future.result()
            completed_by_grad[grad] += 1

            if board is not None and solution is not None and board not in seen_boards[grad]:
                solved_candidates[grad].append(
                    (len(solution), candidate_number, board, solution)
                )
                seen_boards[grad].add(board)
                print(
                    f"grad {grad}: solved_candidates={len(solved_candidates[grad])} "
                    f"latest_len={len(solution)} candidate={candidate_number}/"
                    f"{GENERATED_CANDIDATES_PER_GRAD}",
                    flush=True,
                )

            if completed_by_grad[grad] % 100 == 0:
                print(
                    f"grad {grad}: completed={completed_by_grad[grad]}/"
                    f"{GENERATED_CANDIDATES_PER_GRAD} "
                    f"solved_unique={len(solved_candidates[grad])}",
                    flush=True,
                )

    generated_by_grad = {}
    incomplete = []
    for grad in GRADS:
        hardest = sorted(
            solved_candidates[grad],
            key=lambda item: (item[0], -item[1]),
            reverse=True,
        )[:BOARDS_PER_GRAD]
        if len(hardest) < BOARDS_PER_GRAD:
            incomplete.append(grad)

        boards = [board for _length, _candidate_number, board, _solution in hardest]
        solutions = [solution for _length, _candidate_number, _board, solution in hardest]
        generated_by_grad[grad] = (boards, solutions)

    if incomplete:
        print(
            "Warning: fewer than requested BFS-solved candidates for grads: "
            f"{incomplete}"
        )

    write_all_solved_candidates(solved_candidates)
    update_injection_file(generated_by_grad)
    print(f"Wrote all solved candidates to {ALL_SOLVED_OUTPUT_PATH}")
    print(f"Updated {INJECTION_PATH}")
    for grad in GRADS:
        boards, solutions = generated_by_grad[grad]
        lengths = [len(solution) for solution in solutions]
        if lengths:
            print(
                f"grad {grad}: wrote {len(boards)} boards / {len(solutions)} solutions "
                f"length_min={min(lengths)} length_max={max(lengths)} "
                f"length_avg={sum(lengths) / len(lengths):.1f}"
            )
        else:
            print(f"grad {grad}: wrote 0 boards / 0 solutions")


if __name__ == "__main__":
    main()
