import importlib.util
import multiprocessing as mp
import os
import queue
import time
from pathlib import Path

from board_generator import BoardGenerator


TRAINING_OUTPUT_PATH = Path(__file__).resolve().parent / "generated_training_boards.py"
EVAL_OUTPUT_PATH = Path(__file__).resolve().parent / "generated_eval_boards.py"
TIMEOUT_SECONDS = 10
MAX_WORKERS = max(1, min((os.cpu_count() or 2) - 1, 8))
TARGET_BOARD_COUNTS = {
    4: {"train": 200, "eval": 75},
    5: {"train": 300, "eval": 100},
    6: {"train": 500, "eval": 150},
    7: {"train": 750, "eval": 200},
    8: {"train": 1000, "eval": 250},
    9: {"train": 1000, "eval": 300},
    10: {"train": 1000, "eval": 300},
}


def load_board_file(path, module_name, var_name):
    if not path.exists():
        return {}
    spec = importlib.util.spec_from_file_location(module_name, path)
    generated_boards = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(generated_boards)
    return dict(getattr(generated_boards, var_name))


def generate_one(grad_num, seed, result_queue):
    try:
        generator = BoardGenerator()
        board = generator.generate(
            grad=grad_num,
            count=1,
            seed=seed,
            verbose=False,
        )[0]
        result_queue.put(("ok", grad_num, seed, board))
    except Exception as exc:
        result_queue.put(("error", grad_num, seed, repr(exc)))


def write_board_file(path, var_name, boards_by_grad, lines_before_var):
    lines = [
        *lines_before_var,
        f"{var_name} = {{\n",
    ]
    for grad_num in sorted(boards_by_grad):
        lines.append(f"    {grad_num}: [\n")
        for board in boards_by_grad[grad_num]:
            lines.append("        (\n")
            for row in board:
                lines.append(f"            {row!r},\n")
            lines.append("        ),\n")
        lines.append("    ],\n")
    lines.append("}\n")
    path.write_text("".join(lines))


def write_training_boards(training_boards):
    write_board_file(
        TRAINING_OUTPUT_PATH,
        "TRAINING_BOARDS",
        training_boards,
        [
            "# Auto-generated by regenerate_training_boards_4_to_10.py.\n",
            "# Grads outside 4-10 are preserved from the previous generated_training_boards.py.\n",
        ],
    )


def write_eval_boards(eval_boards):
    write_board_file(
        EVAL_OUTPUT_PATH,
        "EVAL_BOARDS",
        eval_boards,
        [
            "# Auto-generated by regenerate_training_boards_4_to_10.py.\n",
            "# Held-out boards for eval; do not train on these.\n",
        ],
    )


def stop_process(process):
    if process.is_alive():
        process.terminate()
    process.join(timeout=1)
    if process.is_alive():
        process.kill()
        process.join()


def drain_results(result_queue):
    results = []
    while True:
        try:
            results.append(result_queue.get_nowait())
        except queue.Empty:
            return results


def generate_grad(ctx, grad_num, count):
    result_queue = ctx.Queue()
    boards = []
    seen = set()
    active = {}
    next_seed = grad_num
    timed_out = 0
    failed = 0
    duplicates = 0

    print(
        f"Generating grad {grad_num}: {count} boards "
        f"with timeout={TIMEOUT_SECONDS}s workers={MAX_WORKERS}",
        flush=True,
    )

    try:
        while len(boards) < count:
            while len(active) < MAX_WORKERS and len(boards) + len(active) < count + MAX_WORKERS:
                process = ctx.Process(
                    target=generate_one,
                    args=(grad_num, next_seed, result_queue),
                )
                process.start()
                active[next_seed] = (process, time.monotonic())
                next_seed += 1

            for status, result_grad, seed, payload in drain_results(result_queue):
                active_process = active.pop(seed, None)
                if active_process is not None:
                    active_process[0].join(timeout=1)

                if result_grad != grad_num:
                    continue
                if status == "ok":
                    if payload in seen:
                        duplicates += 1
                        print(
                            f"  duplicate seed={seed}; accepted={len(boards)}/{count}",
                            flush=True,
                        )
                    else:
                        seen.add(payload)
                        boards.append(payload)
                        print(
                            f"  accepted {len(boards)}/{count} seed={seed}",
                            flush=True,
                        )
                else:
                    failed += 1
                    print(
                        f"  seed={seed} failed; accepted={len(boards)}/{count}: {payload}",
                        flush=True,
                    )

            now = time.monotonic()
            for seed, (process, started_at) in list(active.items()):
                if now - started_at > TIMEOUT_SECONDS:
                    stop_process(process)
                    active.pop(seed, None)
                    timed_out += 1
                    print(
                        f"  seed={seed} timed out; accepted={len(boards)}/{count}",
                        flush=True,
                    )

            time.sleep(0.05)
    finally:
        for process, _ in active.values():
            stop_process(process)

    print(
        f"Finished grad {grad_num}: accepted={len(boards)} "
        f"timed_out={timed_out} failed={failed} duplicates={duplicates}",
        flush=True,
    )
    return boards


def main():
    training_boards = load_board_file(
        TRAINING_OUTPUT_PATH,
        "generated_training_boards",
        "TRAINING_BOARDS",
    )
    eval_boards = load_board_file(
        EVAL_OUTPUT_PATH,
        "generated_eval_boards",
        "EVAL_BOARDS",
    )
    ctx = mp.get_context("spawn")

    for grad_num, counts in TARGET_BOARD_COUNTS.items():
        train_count = counts["train"]
        eval_count = counts["eval"]
        total_count = train_count + eval_count
        boards = generate_grad(ctx, grad_num, total_count)
        training_boards[grad_num] = boards[:train_count]
        eval_boards[grad_num] = boards[train_count:]
        write_training_boards(training_boards)
        write_eval_boards(eval_boards)
        print(
            f"Saved grad {grad_num}: train={train_count} into {TRAINING_OUTPUT_PATH}, "
            f"eval={eval_count} into {EVAL_OUTPUT_PATH}",
            flush=True,
        )

    print(
        f"Done. Updated train and eval only for grads: {sorted(TARGET_BOARD_COUNTS)}",
        flush=True,
    )


if __name__ == "__main__":
    main()
